name: aitebar

description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: 3.7.5


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  flutter_bloc: ^8.1.2
  dio: ^5.0.1
  freezed_annotation: ^2.2.0
  flutter_gen: ^5.2.0
  auto_route: ^5.0.4
  get_it: ^7.2.0
  flutter_svg: ^2.0.2
  injectable: ^2.1.0
  equatable: ^2.0.5
  line_icons: ^2.0.1
  cupertino_icons: ^1.0.5
  json_annotation: ^4.8.0
  fluttertoast: ^8.2.1
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  logger: ^1.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  freezed: ^2.3.2
  flutter_gen_runner: ^5.2.0
  auto_route_generator: ^5.0.3
  injectable_generator: ^2.1.4
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  # assets
  assets:
    - assets/app/
    - assets/svg/
  # fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
